### ISSUE TITLE
ValueError when parsing log file

### ISSUE THREAD

**Issue by walbermr** [dark-0ne/RcssAnalyzer#1]
Hello, I am trying to use the analyzer you developed but I am having some issues when using it.

I'm using python3.6 as you pointed in the repo, my rcssserver version is 15.4 and I also tried with version 15.5 but when I try to parse the log file I get this error after finished extraction:

` Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
    return self.func(*args)
  File "main.py", line 82, in _open_log_file
    analyzer.extract_log_file()
  File "/home/walber/Desktop/robocin/RcssAnalyzer/Analyzer.py", line 142, in extract_log_file
    player = {'Side': 'Right', 'Unum': int(splited[2].split('_')[1][:-1])}
ValueError: invalid literal for int() with base 10: 'bas'
`

I suspect that the log files pattern differ from one server version to another, can you specify which version do you use, so I can test that.

Thanks in advance.

**Comment by dark-0ne** [comment]
Hey walber, thank you for opening this issue and my apologies for responding with delay as I was away for a couple of days.

Truth is this little project of mine has been in an unfinished state for a quite a while now as I hadn't had the time to work on it.
As of this version I don't think the analyzer works even on the version of rcssserver that I used originally when developing it so the problem you mentioned probably isn't on your end but on the project itself. 

That being said I can also promise you that I have plans of continuing the development - and maintenance - for analyzer in near future though can't give an exact schedule but in a few weeks tops I'll begin working on it again starting with a huge refactoring phase - I don't know if you have looked at the source code but currently it's a mess :D 

So, sorry for having your time wasted on a broken project but to you and any other user of this little analyzer: stay tuned for updates ;)

**Comment by walbermr** [comment]
Hello Danial, don't worry, it's pretty fine to have day offs :). Yes, I looked the source code and made some changes to make it sort of usable but still not completely correct.

The team that I am part have interest in this tool and is open to cooperate. You can contact me if you are interested in that too.

Thanks for the reply!

**Comment by dark-0ne** [comment]
> Hello Danial, don't worry, it's pretty fine to have day offs :). Yes, I looked the source code and made some changes to make it sort of usable but still not completely correct.
> 
> The team that I am part have interest in this tool and is open to cooperate. You can contact me if you are interested in that too.
> 
> Thanks for the reply!

Hey again walber, thank you for the offer I would really appreciate the help ;) just give me couple of days to wrap up my exams and I'll get started here and I'll contact you. 

And btw feel free to open a pull request if you think your mentioned changes are an improvement on any part of the project(pretty sure they are cuz the code probably cant get any worse at this state :D )
